on:
  workflow_dispatch:
  push:
    tags:
      - "*"

name: Update latest tag
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Latest tag
        uses: EndBug/latest-tag@v1.4.0
